
<footer class="w3-center" style="background-color:orange;">
    <div>
      <br>
	<h4 style="color:white;">Yhteistyössä</h4>
	<div class="center">
		<a href="http://www.metropolia.fi/"><img src="http://henkilokohtainenbudjetointi.fi/wp-content/themes/digital-pro/images/footer-logos/Metropolia-nega.png" title="Metropolia logo" alt="Metropolia logo" width="174" height="40"></a>
		<a href="http://sote.kainuu.fi/index.asp"><img src="http://henkilokohtainenbudjetointi.fi/wp-content/themes/digital-pro/images/footer-logos/kainuu-nega.png" title="Kainuu sote logo" alt="Kainuu sote logo" width="132" height="40"></a>
	</div>
      <p style="color:white;">Powered by <a href="https://www.w3schools.com/w3css/default.asp" target="_blank">w3.css</a></p>
    </div>  
      </footer>
      </body>
</html>